# Generated by Django 2.1.10 on 2019-12-09 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=11, unique=True, verbose_name='手机')),
                ('phone', models.CharField(max_length=13, verbose_name='座机')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='学校')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='专业')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='居住住址')),
                ('aboutme', models.CharField(blank=True, max_length=200, verbose_name='自我介绍')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='照片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('position', models.ManyToManyField(related_name='UserPosition', to='Department.Position', verbose_name='职位')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '扩展用户信息',
                'db_table': 'auth_user_userextension',
                'ordering': ('-create_time',),
                'permissions': (('sepecial', 'Can publish article'),),
            },
        ),
    ]
