# Generated by Django 2.1.10 on 2019-12-09 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=100, verbose_name='组名称')),
                ('groupNameRemarks', models.CharField(blank=True, max_length=256, null=True, verbose_name='组备注')),
                ('projectName', models.CharField(max_length=100, verbose_name='项目名称')),
                ('projectNameRemarks', models.CharField(blank=True, max_length=256, null=True, verbose_name='项目备注')),
                ('projectDict', models.CharField(max_length=100, verbose_name='项目字典')),
                ('projectKey', models.CharField(max_length=100, verbose_name='项目字典关键字')),
                ('projectValue', models.CharField(max_length=100, verbose_name='项目字典值')),
                ('projectValueRemarks', models.CharField(blank=True, max_length=256, null=True, verbose_name='项目字典值备注')),
                ('projectExtend1', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目备用1')),
                ('projectExtend2', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目备用2')),
                ('projectExtend3', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目备用3')),
                ('projectExtend4', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目备用4')),
                ('projectExtend5', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目备用5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicDataCreateName', to=settings.AUTH_USER_MODEL, verbose_name='创建记录员工')),
                ('lastEditName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicDataLastEditName', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑员工')),
            ],
            options={
                'verbose_name_plural': '基础数据',
                'db_table': 'basicData',
                'ordering': ('groupName', 'projectName', 'projectDict', 'projectKey', 'projectValue'),
            },
        ),
    ]
