# Generated by Django 2.1.10 on 2019-12-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=200, unique=True, verbose_name='部门名称')),
                ('remarksInformation', models.CharField(blank=True, max_length=255, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '部门',
                'db_table': 'department',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('remarksInformation', models.CharField(blank=True, max_length=255, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_position', to='Department.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name_plural': '职位',
                'db_table': 'department_position',
                'ordering': ('-create_time',),
            },
        ),
    ]
